# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-29 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nip', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='stack',
            name='skill',
        ),
        migrations.AddField(
            model_name='skill',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='nip.Stack'),
            preserve_default=False,
        ),
    ]
