# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-29 17:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nip', '0002_auto_20180329_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stack',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_stack', to='nip.User'),
        ),
    ]
