# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-29 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nip', '0003_auto_20180329_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='user',
            field=models.ManyToManyField(null=True, related_name='strengths', to='nip.User'),
        ),
    ]
